name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Prepare build scripts
      run: sudo chmod +x build.sh && sudo chmod +x build-pkgbuild.sh

    - name: Run build
      run: ./build.sh

    - name: Copy data to downloads folder
      run: |
        mkdir artifacts -p
        cp PKGBUILD artifacts
        cp supabase_*_linux_amd64.tar.gz artifacts
        cp supabase-bin-*-x86_64.pkg.tar.zst artifacts

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: artifacts
